import type {Candidate,CampaignEvent,PromiseRecord,AgendaItem,DebateMessage,Polling,PolicyPlan} from './types';
import {BASE_ECONOMY,recalculateEconomy} from './economy';
import {agendaForDay} from './agenda';
import {POLICY_PLANS,selectedPlans} from './plans';
export const candidates:Candidate[]=[{id:'you',name:'Você',party:'Partido da Mudança',ideology:'centro',support:38,personality:'candidato principal',strengths:['comunicação'],weaknesses:['pouca experiência nacional']},{id:'ana',name:'Ana Martins',party:'Partido Social',ideology:'centro-esquerda',support:25,personality:'técnica e incisiva',strengths:['políticas sociais'],weaknesses:['fiscalidade']},{id:'bruno',name:'Bruno Costa',party:'Partido Liberal',ideology:'centro-direita',support:22,personality:'combativo e econômico',strengths:['economia'],weaknesses:['políticas sociais']},{id:'carla',name:'Carla Mendes',party:'Partido Verde',ideology:'ecologista',support:15,personality:'calma e preparada',strengths:['meio ambiente'],weaknesses:['baixa estrutura'] }];
export interface CampaignState{phase:'setup'|'campaign';day:number;candidate:Candidate;opponents:Candidate[];approval:number;polling:Polling;promises:PromiseRecord[];selectedPlans:PolicyPlan[];economy:any;events:CampaignEvent[];agenda:AgendaItem[];chat:DebateMessage[];activeEventId:string|null;memory:string[];issues:Record<string,number>;}
export function createCampaign():CampaignState{const all=structuredClone(candidates);return{phase:'setup',day:0,candidate:all[0],opponents:all.slice(1),approval:50,polling:{you:38,ana:25,bruno:22,carla:15},promises:[],selectedPlans:[],economy:{...BASE_ECONOMY,deficit:100_000_000_000,fiscalHeadroom:100_000_000_000},events:[],agenda:[],chat:[],activeEventId:null,memory:[],issues:{economy:50,health:50,security:50,education:50,environment:50}}}
export function startCampaign(s:CampaignState,ids:string[]){const plans=selectedPlans(ids);s.phase='campaign';s.day=1;s.selectedPlans=plans;s.promises=plans.map(p=>({text:p.details,day:1,impact:{},estimate:{annualCost:p.annualCost,financing:p.revenueEffect,netCost:Math.max(0,p.annualCost-p.revenueEffect),beneficiaries:0,confidence:'plano de governo predefinido',fiscalRatio:Math.max(0,p.annualCost-p.revenueEffect)/BASE_ECONOMY.revenue,inflationRisk:Math.max(0,p.annualCost-p.revenueEffect)/BASE_ECONOMY.revenue*120,growthEffect:p.economicEffects.includes('investimento')?1.5:0,socialBenefit:p.category==='Social'||p.category==='Saúde'?5:2,fiscalStress:Math.max(0,p.annualCost-p.revenueEffect)/BASE_ECONOMY.revenue*100,politicalAppeal:2},}));s.economy=recalculateEconomy(s.promises,s.day);s.agenda=agendaForDay(1,[s.candidate,...s.opponents]);s.events=[{type:'system',title:'Plano de governo registrado',text:`Você iniciou a campanha com ${plans.length} compromissos. Jornalistas e adversários terão acesso às propostas e poderão cobrar custos, metas e financiamento.`,day:1}];s.memory=[`Plano escolhido: ${plans.map(p=>p.title).join(', ')}.`];recalcPolitics(s);return s}
export function recalcPolitics(s:CampaignState){const appeal=s.selectedPlans.reduce((n,p)=>n+2,0),fiscalPenalty=s.economy.deficit>BASE_ECONOMY.expenditure-BASE_ECONOMY.revenue?s.selectedPlans.reduce((n,p)=>n+Math.max(0,p.annualCost-p.revenueEffect)/BASE_ECONOMY.revenue*15,0):0,economyPenalty=Math.max(0,s.economy.inflation-BASE_ECONOMY.inflation)*.7;s.approval=Math.min(100,Math.max(0,50+appeal-fiscalPenalty-economyPenalty));const p=Math.min(70,Math.max(1,s.approval*.55+20)),rem=100-p,other=s.opponents.reduce((n,o)=>n+o.support,0);s.polling.you=+p.toFixed(1);s.opponents.forEach(o=>{s.polling[o.id as keyof Polling]=+Math.max(.5,o.support*rem/other).toFixed(1)})}
export function advanceDay(s:CampaignState){s.day++;s.economy=recalculateEconomy(s.promises,s.day);s.agenda=agendaForDay(s.day,[s.candidate,...s.opponents]);s.events.unshift({type:'system',title:`Dia ${s.day} — nova agenda`,text:'Uma nova rodada de compromissos está disponível. Você precisará escolher onde aparecer.',day:s.day});recalcPolitics(s)}
export {POLICY_PLANS};
