import 'dotenv/config';
import express from 'express';

const app=express(); app.use(express.json());
const PORT=Number(process.env.PORT||3001),AI_URL=process.env.AI_URL||'http://127.0.0.1:11434/api/chat',AI_MODEL=process.env.AI_MODEL||'qwen3:8b';
// Fictional baseline: internal game economy, not a real-world forecast.
const BASE_ECONOMY={gdp:10_000_000_000_000,revenue:3_200_000_000_000,expenditure:3_300_000_000_000,debt:7_500_000_000_000,inflation:4.5,unemployment:7.0,interest:10.0};
const initial={day:1,candidate:{name:'Você',party:'Partido da Mudança',funds:1_000_000},opponents:[{id:'ana',name:'Ana Martins',party:'Partido Social',ideology:'centro-esquerda',support:25},{id:'bruno',name:'Bruno Costa',party:'Partido Liberal',ideology:'centro-direita',support:22},{id:'carla',name:'Carla Mendes',party:'Partido Verde',ideology:'ecologista',support:15}],issues:{economy:50,health:50,security:50,education:50,environment:50},approval:50,polling:{you:38,ana:25,bruno:22,carla:15},promises:[] as any[],economy:{...BASE_ECONOMY,deficit:BASE_ECONOMY.expenditure-BASE_ECONOMY.revenue,fiscalHeadroom:100_000_000_000},events:[{type:'system',title:'Campanha iniciada',text:'A eleição começou. Promessas serão avaliadas pelo impacto fiscal, econômico, social e político. O benefício eleitoral nunca é calculado isoladamente.'}],chat:[] as any[]};
let state=structuredClone(initial); const clamp=(n:number,min=0,max=100)=>Math.min(max,Math.max(min,n)); const money=(n:number)=>Math.round(n/1_000_000)*1_000_000;
function impactFromText(text:string){const t=text.toLowerCase(),i:any={economy:0,health:0,security:0,education:0,environment:0};if(/emprego|econom|imposto|salário|renda|indústria/.test(t))i.economy=4;if(/saúde|hospital|sus|médic/.test(t))i.health=4;if(/segurança|polícia|crime|violência/.test(t))i.security=4;if(/educa|escola|professor|universidade/.test(t))i.education=4;if(/clima|ambient|floresta|energia limpa/.test(t))i.environment=4;return i;}
function extractAmount(text:string){const t=text.toLowerCase().replace(/\./g,'').replace(/,/g,'.'),m=[...t.matchAll(/r\$\s*(\d+(?:\.\d+)?)\s*(milh(?:ão|ões)|bilh(?:ão|ões)|mil)?/gi)];if(!m.length)return null;let total=0;for(const x of m){const n=Number(x[1]),u=x[2]||'';total+=u.startsWith('bilh')?n*1e9:u.startsWith('milh')?n*1e6:u==='mil'?n*1e3:n;}return total;}
function extractPeople(text:string){const t=text.toLowerCase().replace(/,/g,'.');const m=t.match(/(\d+(?:\.\d+)?)\s*(milh(?:ão|ões)|mil|pessoas|famílias)/);if(!m)return null;const n=Number(m[1]);return m[2].startsWith('milh')?n*1e6:m[2]==='mil'?n*1e3:n;}
function estimatePromise(text:string){
 const t=text.toLowerCase(),explicit=extractAmount(text);let annualCost=0,beneficiaries=0,confidence='estimativa';
 if(/bolsa.?família|bolsa|auxílio|benefício|renda mínima/.test(t)){
   const monthly=explicit||2_000;
   // Fictional beneficiary pool. A promise cannot silently assume only a few thousand people.
   beneficiaries=extractPeople(text)||(t.includes('bolsa')?20_000_000:10_000);
   annualCost=monthly*12*beneficiaries; confidence='estimativa por benefício mensal e população afetada';
 } else if(explicit){annualCost=explicit;confidence='valor explícito da promessa';}
 else if(/construir|construção|hospital|escola|ferrovia|rodovia|creche|universidade/.test(t)){annualCost=200_000_000;confidence='estimativa por programa de investimento';}
 else if(/aumentar|criar|reduzir|isentar|subsidiar|gratuit/.test(t)){annualCost=100_000_000;confidence='estimativa preliminar';}
 annualCost=money(annualCost);
 // Revenue measures can finance part of a spending promise. Only explicit amounts count as financing.
 const financing=/aumentar imposto|criar imposto|elevar imposto|tributar|receita adicional|arrecadar/.test(t)&&explicit?money(explicit):0;
 const netCost=Math.max(0,annualCost-financing),fiscalRatio=netCost/BASE_ECONOMY.revenue;
 const inflationRisk=clamp(fiscalRatio*120,0,12),growthEffect=/investimento|infraestrutura|emprego|produtiv/.test(t)?clamp(netCost/BASE_ECONOMY.gdp*180,0,4):0;
 const socialBenefit=/bolsa|auxílio|saúde|hospital|educa|escola|creche|salário|renda/.test(t)?clamp(annualCost/BASE_ECONOMY.gdp*80,0,8):2;
 const fiscalStress=clamp(fiscalRatio*100,0,100),politicalAppeal=clamp(socialBenefit-fiscalStress*.35+growthEffect*.5,-15,12);
 return {annualCost,financing,netCost,beneficiaries,confidence,fiscalRatio,inflationRisk,growthEffect,socialBenefit,fiscalStress,politicalAppeal};
}
function recalculateEconomy(){const recurring=state.promises.reduce((s:number,p:any)=>s+(p.estimate?.netCost||0),0),financing=state.promises.reduce((s:number,p:any)=>s+(p.estimate?.financing||0),0),deficit=BASE_ECONOMY.expenditure+recurring-BASE_ECONOMY.revenue-financing,debt=BASE_ECONOMY.debt+Math.max(0,deficit)*Math.max(1,state.day/30),fiscalRatio=recurring/BASE_ECONOMY.revenue,inflationRisk=state.promises.reduce((s:number,p:any)=>s+(p.estimate?.inflationRisk||0),0);state.economy={...state.economy,revenue:BASE_ECONOMY.revenue+financing,expenditure:BASE_ECONOMY.expenditure+recurring,deficit,debt,inflation:clamp(BASE_ECONOMY.inflation+fiscalRatio*18+inflationRisk*.15,0,30),unemployment:clamp(BASE_ECONOMY.unemployment-state.promises.reduce((s:number,p:any)=>s+(p.estimate?.growthEffect||0)*.15,0),2,25),fiscalHeadroom:Math.max(0,BASE_ECONOMY.revenue+financing-BASE_ECONOMY.expenditure-recurring)};}
function recalculatePolitics(){const appeal=state.promises.reduce((s:number,p:any)=>s+(p.estimate?.politicalAppeal||0),0),fiscalPenalty=state.promises.reduce((s:number,p:any)=>s+Math.max(0,(p.estimate?.fiscalStress||0)-3)*.18,0),economyPenalty=Math.max(0,state.economy.inflation-BASE_ECONOMY.inflation)*.7;state.approval=clamp(50+appeal-fiscalPenalty-economyPenalty);const p=clamp(state.approval*.55+20,1,70),remainder=100-p,others=state.opponents.reduce((s:any,o:any)=>s+o.support,0);state.polling.you=Math.round(p*10)/10;state.opponents.forEach((o:any)=>state.polling[o.id]=Math.max(.5,Math.round(o.support*remainder/others*10)/10));}
function localAi(prompt:string){const l=prompt.toLowerCase();if(l.includes('debate'))return'Você fala primeiro. Seu adversário reage com uma pergunta direta sobre sua proposta e tenta explorar qualquer contradição do seu discurso.';if(l.includes('reportagem'))return'BOLETIM — A campanha ganhou repercussão. Analistas discutem custos, viabilidade e efeitos das propostas apresentadas.';return'A campanha continua. Uma decisão pode gerar benefícios para determinados grupos e custos econômicos ou políticos para outros.';}
async function ai(prompt:string){try{const headers:any={'Content-Type':'application/json'};if(process.env.AI_API_KEY)headers.Authorization=`Bearer ${process.env.AI_API_KEY}`;const body={model:AI_MODEL,messages:[{role:'system',content:'Você é o motor narrativo de um simulador eleitoral fictício. Seja imparcial, trate todos os candidatos como personagens fictícios, crie consequências coerentes e nunca diga ao jogador em quem votar. Responda em português do Brasil.'},{role:'user',content:prompt}],stream:false};const r=await fetch(AI_URL,{method:'POST',headers,body:JSON.stringify(body)});if(!r.ok)throw new Error(`AI ${r.status}`);const d:any=await r.json();return d.message?.content||d.choices?.[0]?.message?.content||localAi(prompt);}catch{return localAi(prompt);}}
app.get('/api/state',(_,res)=>res.json(state)); app.post('/api/reset',(_,res)=>{state=structuredClone(initial);res.json(state);});
app.post('/api/action',async(req,res)=>{const {type,text}=req.body||{};
 if(type==='promise'){const estimate=estimatePromise(text||''),impact=impactFromText(text||'');state.promises.push({text,day:state.day,impact,estimate});Object.keys(impact).forEach(k=>state.issues[k as keyof typeof state.issues]=clamp(state.issues[k as keyof typeof state.issues]+impact[k]));state.events.unshift({type:'promise',title:'Nova promessa — análise fiscal',text:`${text} | Custo bruto: R$ ${estimate.annualCost.toLocaleString('pt-BR')}/ano | Financiamento: R$ ${estimate.financing.toLocaleString('pt-BR')} | Custo líquido: R$ ${estimate.netCost.toLocaleString('pt-BR')}/ano | Beneficiários: ${estimate.beneficiaries.toLocaleString('pt-BR')} | Pressão fiscal: ${estimate.fiscalStress.toFixed(1)}%. ${estimate.confidence}.`});recalculateEconomy();recalculatePolitics();}
 if(type==='day'){state.day++;recalculateEconomy();state.approval=clamp(state.approval+(Math.random()-.5)*6);recalculatePolitics();const report=await ai(`Crie uma reportagem curta para o dia ${state.day} de uma eleição presidencial fictícia. Economia: inflação ${state.economy.inflation.toFixed(1)}%, déficit R$ ${state.economy.deficit.toLocaleString('pt-BR')}, dívida R$ ${state.economy.debt.toLocaleString('pt-BR')}. Últimas promessas e custos: ${state.promises.slice(-3).map((p:any)=>`${p.text} (líquido R$ ${p.estimate?.netCost?.toLocaleString('pt-BR')||0}/ano)`).join(' | ')}. Mostre reações e questionamentos sobre viabilidade sem favorecer ninguém.`);state.events.unshift({type:'news',title:`Boletim eleitoral — Dia ${state.day}`,text:report});}
 if(type==='debate'){const reply=await ai(`Simule um debate presidencial fictício. O jogador acabou de dizer: "${text}". Dados fiscais: déficit R$ ${state.economy.deficit.toLocaleString('pt-BR')}; inflação ${state.economy.inflation.toFixed(1)}%; custo líquido anual das promessas R$ ${state.promises.reduce((n:number,p:any)=>n+(p.estimate?.netCost||0),0).toLocaleString('pt-BR')}. Responda como ${state.opponents[0].name}, candidata fictícia. Questione números, financiamento e efeitos das propostas, sem insultos pessoais. Termine com uma pergunta.`);state.chat.push({role:'opponent',name:state.opponents[0].name,text:reply,day:state.day});}
 if(type==='statement'){const reply=await ai(`Analise esta declaração de campanha fictícia: "${text}". Considere a situação fiscal: déficit R$ ${state.economy.deficit.toLocaleString('pt-BR')}, inflação ${state.economy.inflation.toFixed(1)}% e custo líquido anual das promessas R$ ${state.promises.reduce((n:number,p:any)=>n+(p.estimate?.netCost||0),0).toLocaleString('pt-BR')}. Gere reação de jornalistas, eleitores favoráveis, críticos e indecisos. Não preveja resultado eleitoral real.`);state.events.unshift({type:'news',title:'Repercussão da declaração',text:reply});}
 res.json(state);});
app.listen(PORT,()=>console.log(`President Simulator API: http://localhost:${PORT}`));