import 'dotenv/config';
import express from 'express';
import {createCampaign,recalcPolitics,advanceDay} from './campaign';
import {estimatePromise,recalculateEconomy} from './economy';
import type {CampaignState} from './campaign';
const app=express();app.use(express.json());const PORT=Number(process.env.PORT||3001),AI_URL=process.env.AI_URL||'http://127.0.0.1:11434/api/chat',AI_MODEL=process.env.AI_MODEL||'qwen3:8b';let state:CampaignState=createCampaign();
const clamp=(n:number,min=0,max=100)=>Math.min(max,Math.max(min,n));
function impact(text:string){const t=text.toLowerCase(),i:any={economy:0,health:0,security:0,education:0,environment:0};if(/emprego|econom|imposto|salário|renda|indústria/.test(t))i.economy=4;if(/saúde|hospital|sus|médic/.test(t))i.health=4;if(/segurança|polícia|crime|violência/.test(t))i.security=4;if(/educa|escola|professor|universidade/.test(t))i.education=4;if(/clima|ambient|floresta|energia limpa/.test(t))i.environment=4;return i}
function fallback(prompt:string){const l=prompt.toLowerCase();if(l.includes('debate'))return'PERGUNTA DO ADVERSÁRIO: Sua proposta parece popular, mas os números ainda precisam ser explicados. Qual é a fonte de financiamento e quais serão as consequências para as contas públicas?';if(l.includes('entrevista'))return'O jornalista pede detalhes sobre sua proposta, questiona números e compara sua declaração com o que você já afirmou durante a campanha.';return'A imprensa registra a declaração e analistas passam a discutir seus custos, viabilidade e possíveis efeitos.'}
async function ai(prompt:string){try{const r=await fetch(AI_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:AI_MODEL,messages:[{role:'system',content:'Você é o motor narrativo de uma campanha presidencial fictícia. Nunca decide a eleição nem atribui números eleitorais diretamente. Respeite o histórico fornecido. Interprete candidatos, jornalistas e moderadores com personalidades distintas. Faça perguntas e réplicas realistas, sem insultos pessoais.'},{role:'user',content:prompt}],stream:false})});if(!r.ok)throw 0;const d:any=await r.json();return d.message?.content||d.choices?.[0]?.message?.content||fallback(prompt)}catch{return fallback(prompt)}}
app.get('/api/state',(_,res)=>res.json(state));app.post('/api/reset',(_,res)=>{state=createCampaign();res.json(state)});
app.post('/api/agenda/select',async(req,res)=>{const {eventId}=req.body||{},e=state.agenda.find(x=>x.id===eventId);if(!e)return res.status(404).json({error:'Evento não encontrado'});if(e.status!=='available')return res.status(409).json({error:'Evento indisponível'});e.status='completed';state.activeEventId=e.id;state.chat=[];const rival=e.targetCandidate?state.opponents.find(o=>o.id===e.targetCandidate)?.name:'todos os candidatos';const prompt=e.type==='debate_all'?`Inicie um debate presidencial fictício ao vivo com ${state.opponents.map(o=>o.name).join(', ')} e o jogador. Tema inicial: economia. Faça a abertura do moderador e uma pergunta ao jogador.`:e.type==='debate_one'?`Inicie um confronto presidencial individual entre Você e ${rival}. Faça o mediador apresentar o confronto e o adversário formular a primeira pergunta.`:e.type==='interview'?`Inicie uma entrevista para ${e.outlet}. O jornalista deve fazer uma pergunta difícil sobre as propostas recentes e as contas públicas.`:`Inicie uma coletiva de imprensa. Um jornalista faz a primeira pergunta sobre a campanha.`;const reply=await ai(`${prompt}\nContexto fiscal: inflação ${state.economy.inflation.toFixed(1)}%, déficit R$ ${state.economy.deficit.toLocaleString('pt-BR')}, custo líquido anual das promessas R$ ${state.promises.reduce((n,p)=>n+p.estimate.netCost,0).toLocaleString('pt-BR')}. Memória recente: ${state.memory.slice(-8).join(' | ')}`);state.chat.push({eventId:e.id,role:e.type==='interview'||e.type==='press_conference'?'journalist':'moderator',speaker:e.type==='interview'?e.outlet||'Jornalista':'Moderador',text:reply,day:state.day});res.json(state)});
app.post('/api/action',async(req,res)=>{const {type,text}=req.body||{};if(type==='promise'){const estimate=estimatePromise(text||''),im=impact(text||'');state.promises.push({text,day:state.day,impact:im,estimate});Object.keys(im).forEach(k=>state.issues[k]=clamp(state.issues[k]+im[k]));state.economy=recalculateEconomy(state.promises,state.day);recalcPolitics(state);state.memory.push(`Dia ${state.day}: promessa — ${text} | custo líquido ${estimate.netCost}`);state.events.unshift({type:'promise',title:'Promessa registrada e calculada',text:`${text} • custo bruto ${estimate.annualCost.toLocaleString('pt-BR')}/ano • custo líquido ${estimate.netCost.toLocaleString('pt-BR')}/ano • pressão fiscal ${estimate.fiscalStress.toFixed(1)}%`,day:state.day})}else if(type==='day'){advanceDay(state)}else if(type==='chat'){if(!state.activeEventId)return res.status(409).json({error:'Escolha um compromisso da agenda primeiro'});const e=state.agenda.find(x=>x.id===state.activeEventId)!;state.chat.push({eventId:e.id,role:'player',speaker:'Você',text,day:state.day});const prompt=`Evento: ${e.title}. Tipo: ${e.type}. Última fala do jogador: "${text}". Responda como participante apropriado. Se debate coletivo, alterne entre candidatos e mantenha conflito de ideias; se individual, permita réplica e tréplica; se entrevista, atue como jornalista. Use as promessas e declarações anteriores como memória. Situação fiscal: ${JSON.stringify(state.economy)}. Promessas: ${state.promises.map(p=>`${p.text} [líquido ${p.estimate.netCost}]`).join(' | ')}. Memória: ${state.memory.slice(-10).join(' | ')}. Termine com uma pergunta ou reação que permita ao jogador continuar.`;const reply=await ai(prompt);const role=e.type==='interview'||e.type==='press_conference'?'journalist':'opponent';const speaker=e.type==='debate_one'?state.opponents.find(o=>o.id===e.targetCandidate)?.name:e.type==='debate_all'?state.opponents[(state.chat.length-1)%state.opponents.length].name:e.outlet||'Jornalista';state.chat.push({eventId:e.id,role,speaker,text:reply,day:state.day});state.memory.push(`Dia ${state.day}, ${e.title}: jogador disse "${text}"; resposta: "${reply}"`);state.events.unshift({type:'repercussion',title:`Repercussão — ${e.title}`,text:reply,day:state.day})}else if(type==='day_end'){advanceDay(state)}res.json(state)});
app.listen(PORT,()=>console.log(`President Simulator API: http://localhost:${PORT}`));