export interface PolicyPlan { id:string; title:string; category:string; summary:string; details:string; annualCost:number; revenueEffect:number; politicalRisks:string[]; economicEffects:string[]; journalistAngles:string[]; }
export const POLICY_PLANS:PolicyPlan[]=[
{id:'family-income',title:'Renda e proteção social',category:'Social',summary:'Ampliar transferências de renda com reajuste gradual e focalização.',details:'Reajuste moderado dos benefícios, revisão cadastral e expansão limitada da cobertura.',annualCost:72_000_000_000,revenueEffect:0,politicalRisks:['pressão fiscal','questionamentos sobre focalização'],economicEffects:['redução de pobreza','aumento de consumo das famílias de baixa renda'],journalistAngles:['fonte de financiamento','impacto no déficit','número de beneficiários']},
{id:'health',title:'Saúde pública',category:'Saúde',summary:'Expandir atenção básica, filas de especialidades e infraestrutura do SUS.',details:'Plano plurianual para atenção básica, hospitais regionais e redução de filas.',annualCost:55_000_000_000,revenueEffect:0,politicalRisks:['execução orçamentária','custo de infraestrutura'],economicEffects:['melhora do acesso','ganhos de produtividade por redução de afastamentos'],journalistAngles:['custo por etapa','capacidade de execução','fontes de recursos']},
{id:'education',title:'Educação e primeira infância',category:'Educação',summary:'Ampliar creches, alfabetização e formação de professores.',details:'Expansão gradual de vagas e programas de aprendizagem com metas verificáveis.',annualCost:48_000_000_000,revenueEffect:0,politicalRisks:['prazo de resultados','coordenação federativa'],economicEffects:['capital humano','efeitos de longo prazo na produtividade'],journalistAngles:['metas','prazo','financiamento']},
{id:'security',title:'Segurança pública',category:'Segurança',summary:'Investir em inteligência, integração policial e prevenção de crimes violentos.',details:'Integração de bases, inteligência financeira e programas de prevenção.',annualCost:36_000_000_000,revenueEffect:0,politicalRisks:['coordenação com estados','resultados difíceis de medir'],economicEffects:['redução de custos da violência','maior segurança para atividade econômica'],journalistAngles:['competência federal','indicadores de resultado','custo operacional']},
{id:'tax-reform',title:'Reforma tributária e equilíbrio fiscal',category:'Economia',summary:'Revisar subsídios, combater evasão e buscar aumento gradual de receitas.',details:'Medidas de arrecadação e revisão de benefícios fiscais acompanhadas de metas fiscais.',annualCost:8_000_000_000,revenueEffect:95_000_000_000,politicalRisks:['resistência de setores afetados','risco de arrecadação abaixo da estimativa'],economicEffects:['redução do déficit','maior previsibilidade fiscal'],journalistAngles:['quem pagará','estimativa de arrecadação','efeito sobre empresas e famílias']},
{id:'infrastructure',title:'Infraestrutura e emprego',category:'Desenvolvimento',summary:'Programa de investimentos em logística, saneamento e infraestrutura urbana.',details:'Carteira plurianual priorizada por retorno econômico e execução.',annualCost:85_000_000_000,revenueEffect:0,politicalRisks:['atrasos','sobrecusto de obras'],economicEffects:['investimento','emprego','ganho de produtividade'],journalistAngles:['obras prioritárias','custo total','modelo de financiamento']},
{id:'green',title:'Transição energética',category:'Meio ambiente',summary:'Acelerar energia limpa, eficiência e redução de emissões.',details:'Investimentos e incentivos condicionados a metas de eficiência e redução de emissões.',annualCost:42_000_000_000,revenueEffect:12_000_000_000,politicalRisks:['custo de transição','conflito com setores intensivos em energia'],economicEffects:['investimento privado','redução de emissões','diversificação energética'],journalistAngles:['custo da transição','preço da energia','metas ambientais']}
];
export function selectedPlans(ids:string[]){return POLICY_PLANS.filter(p=>ids.includes(p.id));}
